<?php

namespace Database\Seeders;

use App\Models\Pages;
use Illuminate\Database\Seeder;

class AboutUsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $data = [
            "slug" => "about-us",
            "title_am" => "Մեր մասին",
            "desc_am" => '
            <p><span>Guyq.am կայքի ստեղծման կարևորագույն նպատակը անշարժ գույքի շուկայից օգտվող հաճախորդների կարծրատիպը փոխելն է: Ընկերության անձնակազմը համալրված է անշարժ գույքի առք ու վաճառքով զբաղվող փորձառու մասնագետներով, գնահատողներով, իրավաբաններով, շինարարներով, ճարտարապետներով և դիզայներներով, ովքեր մասնագիտական օգնություն են ցուցաբերում անշարժ գույքի հետ կապված բոլոր հարցերում: Հեշտացնելով հաճախորդների որոնումները, մեր մասնագետները անվճար հիմունքներով բազմաթիվ ծառայություններ են իրականացնում: Հաշվի առնելով հայկական սփյուռքի գործոնը և զբոսաշրջիկներին սպասարկելու անհրաժեշտությունը մեր ընկերության աշխատակազմում ներառել ենք ռուսերեն, անգլերեն լեզուների իմացությամբ աշխատակիցներ: Աշխատանքում ընկերությունը անվերհապահորեն հետևում է գաղտնիության պահպանման սկզբունքին և հաճախորդի իրական շահերի պաշտպանությանը: Մեր աշխատանքում մենք ձգտում ենք արժանանալ յուրաքանչյուր հաճախորդի գոհունակությանը, որպեսզի նրանք իրենց մտերիմներին վստահորեն ուղորդեն դեպի Guyq.am կայք: Մենք կարևորում ենք մեր հաճախորդների վստահությունը և ձգտում անթերի սպասարկման: Ընկերությունը՝ երաշխավորելով շահավետ, արագ և անվտանգ գործարքներ, տրամադրում է անշարժ գույքի հետ կապված ծառայությունների ամբողջական փաթեթ՝</span></p>
            <p><span>1. Անշարժ գույքի առք, վաճառք և վարձակալություն </span><br /><span>2. Անշարժ գույքի գնահատում <br />3. Շինարարություն </span><br /><span>4. Դիզայն </span><br /><span>5. Վերանորոգում </span><br /><br /><span>Մեր տրամադրության տակ է գտնվում հայաստանյան անշարժ գույքի խոշորագույն բազան:Կայքը հնարավորություն է ընձեռում հաճախորդին գնելու/վաճառելու կամ վարձակալելու/վարձակալության հանձնելու և՛ առաջնային, և՛ երկրորդական շուկայից: Հարմարավետ և հեշտ որոնողական համակարգը թույլ է տալիս հաճախորդին ծանոթանալ առաջարկներին, և իր պահանջներին համապատասխան՝ անշարժ գույքի բազայից կատարել ընտրություն: Կայքից օգտվում են բազմաթիվ գնորդներ/վաճառողներ, ինչպես նաև վարձակալներ/վարձակալության հանձնողներ, որոնց կայքը հնարավորություն է տալիս ծանոթանալ շուկայական գներին: կայքը համագործակցում է առաջատար կառուցապատող ընկերությունների հետ՝ առանձնահատուկ պայմաններով: Guyq.am կայքում ներկայացված են Երևան քաղաքի էկոնոմ և էլիտար դասի բնակարաններ: Անշարժ գույքի առք, վաճառք կամ վարձակալության գործունեության տեսակները՝ <br /><br />1. Վարձով բնակարաններ, վաճառքի ենթակա բնակարաններ <br />2. Վարձով կամ վաճառքի ենթակա գրասենյակային տարածքներ, կոմերցիոն և արտադրական նշանակության տարածքներ <br />3. Բնակարաններ նորակառույց շենքերում՝ եկամտահարկի վերադարձման օրենքի առկայությամբ <br />4. Արտադրական, կոմերցիոն, գյուղատնտեսական և տնամերձ հողատարածքներ Երևան քաղաքում <br />5. Խորհրդատվություն՝ կապված հիփոթեքային վարկերի, նորակառույցներում բնակարանների ձեռքբերման և այլ հարցերի հետ</span></p>
            ',
            "title_en" => "About Us",
            "desc_en" => '<p>The main purpose of creating Guyq.am website is to change the stereotype of customers using the real estate market. The company\'s staff is staffed with experienced real estate professionals, appraisers, lawyers, builders, architects and designers, who provide professional assistance in all matters related to real estate. Facilitating customer search, our specialists provide a wide range of free services. Taking into account the factor of the Armenian Diaspora ությունը the need to serve tourists, we have included employees in our company\'s staff who speak Russian and English. At work, the company unconditionally adheres to the principle of confidentiality, protection of the real interests of the customer. In our work, we strive to satisfy every customer so that they can confidently direct their loved ones to Guyq.am website. We build the trust of our customers և strive for perfect service. The company provides a complete package of real estate services, guaranteeing profitable, fast and safe transactions:</p>
            <p>1. Purchase, sale and rent of real estate<br />2. Real estate appraisal<br />3. Construction<br />4. Design<br />5. Renovation</p>
            <p>We have the largest database of real estate in Armenia. The site allows the client to buy / sell or rent / lease from both the primary and secondary markets. Convenient, easy search engine allows the client to get acquainted with the offers, համապատասխան to make a choice from the real estate database according to his requirements. The site is used by many buyers / sellers, as well as tenants / renters, whose site allows them to get acquainted with market prices. The site cooperates with leading construction companies on special terms. Guyq.am website presents economy class apartments in Yerevan. Types of real estate buying, selling or renting activities:</p>
            <p>1. Apartments for rent, apartments for sale<br />2. Office premises for rent or sale, premises of commercial-industrial significance<br />3. Apartments in newly built buildings with an income tax return law<br />4. Industrial, commercial, agricultural lands near the city of Yerevan<br />5. Consulting on Mortgage Loans, Acquisition of Apartments in New Buildings և Other Issues</p>',
            "title_ru" => "О Нас",
            "desc_ru" => '<p><span>Основной целью создания сайта Guyq.am является изменение стереотипа клиентов, использующих рынок недвижимости. Штат компании состоит из опытных специалистов по недвижимости, оценщиков, юристов, строителей, архитекторов и дизайнеров, которые оказывают профессиональную помощь во всех вопросах, связанных с недвижимостью. Содействуя поиску клиентов, наши специалисты оказывают широкий спектр бесплатных услуг. Принимая во внимание фактор армянской диаспоры ությունը необходимость обслуживания туристов, мы включили в штат нашей компании сотрудников, владеющих русским и английским языками. В работе компания безоговорочно придерживается принципа конфиденциальности, защиты реальных интересов заказчика. В своей работе мы стремимся удовлетворить каждого клиента, чтобы он мог уверенно направлять своих близких на сайт Guyq.am. Мы завоевываем доверие наших клиентов և стремимся к безупречному обслуживанию. Компания предоставляет полный пакет услуг в сфере недвижимости, гарантируя выгодные, быстрые и безопасные сделки:</span></p>
            <p><span>1. Покупка, продажа и аренда недвижимости</span><br /><span>2. Оценка недвижимости</span><br /><span>3. Строительство</span><br /><span>4. Дизайн</span><br /><span>5. Ремонт</span></p>
            <p><span>У нас самая большая база недвижимости в Армении.Площадка позволяет клиенту купить/продать или арендовать/сдать как на первичном, так и на вторичном рынке. Удобная և простая поисковая система позволяет клиенту ознакомиться с предложениями, а также сделать выбор из базы данных недвижимости в соответствии со своими требованиями. Сайтом пользуются многие покупатели/продавцы, а также арендаторы/арендаторы, чей сайт позволяет ознакомиться с рыночными ценами. Сайт сотрудничает с ведущими строительными компаниями на особых условиях. Сайт Guyq.am представляет квартиры эконом-класса в Ереване. Виды деятельности по покупке, продаже или аренде недвижимости:</span></p>
            <p><span>1. Аренда квартир, продажа квартир</span><br /><span>2. Аренда или продажа офисных помещений, помещений торгово-производственного назначения</span><br /><span>3. Квартиры в новостройках с законом о подоходном налоге</span><br /><span>4. Промышленные, коммерческие, сельскохозяйственные земли вблизи г. Еревана</span><br /><span>5. Консультации по ипотечному кредитованию, приобретению квартир в новостройках և Другие вопросы</span></p>',
            'image' => 'images/living-room.png',
        ];
        Pages::create($data);
    }
}
